name: Lint, test, and build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: go-build

defaults:
  run:
    working-directory: ./cloud
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Disable the builtin caching since it uses the hash of the go.sum file
      # to determine if the cache is valid. This is not ideal since the go.sum
      # file is updated every time a new version of a dependency is downloaded.
      # Not when your code changes.
      - name: Set up Golang ${{ matrix.go-version-alias }}
        uses: actions/setup-go@v5
        with:
          go-version-file: ./cloud/go.mod
          cache: false
      # Use restore-keys to always use a cache that was created with the same
      # prefix.
      - name: Cache go modules and the buildcache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-build-${{ github.sha }}
          restore-keys: go-build-
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ./cloud
          version: latest
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out
      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o ./coverage.html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage-report-${{ matrix.go-version-alias }}
          path: ./cloud/coverage.html
      - name: Build
        run: go build -o cloud ./
